### ISSUE TITLE
Multiple Columns with Different Actions

### ISSUE THREAD

**Issue by msalamon1** [compsult/MenuOptions#1]
Wow.  This is an awesome project!

I was curious if an enhancement might be possible for the multi-column situation. Let me explain. Say my data was a list of professional football players and their teams.  I wanted to put the player names in the first column and the teams in the second.  I also want each team name to be a link to the team's web site. When I type in some letters and the autosuggest appears, clicking on a player name will select that player, but clicking on the name would open the team's web site in a different tab. Or the team name could be a js function that opens up a lightbox.  (You have an example like this that uses links and js functions:  http://menuoptions.org/examples/QuickStartMenu.html)

I would likely need to make sure that my data comes in a format that goes: Player, Team, Player, Team, etc. so that the 2nd column is always the team name.   I'm not sure where the team URL would be stored right now.

**Comment by compsult** [comment]
Thanks for the positive feedback. Although it would be a nice feature, right now MenuOptions does not have the capabilities to have rows of related data as part of a menu or an autocomplete. 
I don't know if this would help, but if you could have the Team and player as part of a single menu item, then use mouseover filtering to filter by team (like the 3rd menu on this [example](http://menuoptions.org/examples/MenusBottom.html)). There may be other menu systems that provide what you are looking for but I don't know of them.
